//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hearts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move
    {
        public int MoveId { get; set; }
        public int PlayerId { get; set; }
        public string Move1 { get; set; }
        public System.DateTime Time { get; set; }
        public int GameId { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
